package com.web.model;
// Generated Jan 2, 2017 8:27:41 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Quanlitintuc generated by hbm2java
 */
public class Quanlitintuc  implements java.io.Serializable {


     private Integer idtinTuc;
     private int maTin;
     private String tieuDe;
     private String baiDang;
     private String mota;
     private Date ngayDang;
     private String images;

    public Quanlitintuc() {
    }

	
    public Quanlitintuc(int maTin, String tieuDe, String baiDang, String mota, Date ngayDang) {
        this.maTin = maTin;
        this.tieuDe = tieuDe;
        this.baiDang = baiDang;
        this.mota = mota;
        this.ngayDang = ngayDang;
    }
    public Quanlitintuc(int maTin, String tieuDe, String baiDang, String mota, Date ngayDang, String images) {
       this.maTin = maTin;
       this.tieuDe = tieuDe;
       this.baiDang = baiDang;
       this.mota = mota;
       this.ngayDang = ngayDang;
       this.images = images;
    }
   
    public Integer getIdtinTuc() {
        return this.idtinTuc;
    }
    
    public void setIdtinTuc(Integer idtinTuc) {
        this.idtinTuc = idtinTuc;
    }
    public int getMaTin() {
        return this.maTin;
    }
    
    public void setMaTin(int maTin) {
        this.maTin = maTin;
    }
    public String getTieuDe() {
        return this.tieuDe;
    }
    
    public void setTieuDe(String tieuDe) {
        this.tieuDe = tieuDe;
    }
    public String getBaiDang() {
        return this.baiDang;
    }
    
    public void setBaiDang(String baiDang) {
        this.baiDang = baiDang;
    }
    public String getMota() {
        return this.mota;
    }
    
    public void setMota(String mota) {
        this.mota = mota;
    }
    public Date getNgayDang() {
        return this.ngayDang;
    }
    
    public void setNgayDang(Date ngayDang) {
        this.ngayDang = ngayDang;
    }
    public String getImages() {
        return this.images;
    }
    
    public void setImages(String images) {
        this.images = images;
    }




}


