package com.web.model;
// Generated Nov 22, 2016 8:47:33 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Quanlitintuc generated by hbm2java
 */
public class Quanlitintuc  implements java.io.Serializable {


     private int idtinTuc;
     private String tentintuc;
     private Date ngayDang;
     private String baiDang;

    public Quanlitintuc() {
    }

    public Quanlitintuc(int idtinTuc, String tentintuc, Date ngayDang, String baiDang) {
       this.idtinTuc = idtinTuc;
       this.tentintuc = tentintuc;
       this.ngayDang = ngayDang;
       this.baiDang = baiDang;
    }
   
    public int getIdtinTuc() {
        return this.idtinTuc;
    }
    
    public void setIdtinTuc(int idtinTuc) {
        this.idtinTuc = idtinTuc;
    }
    public String getTentintuc() {
        return this.tentintuc;
    }
    
    public void setTentintuc(String tentintuc) {
        this.tentintuc = tentintuc;
    }
    public Date getNgayDang() {
        return this.ngayDang;
    }
    
    public void setNgayDang(Date ngayDang) {
        this.ngayDang = ngayDang;
    }
    public String getBaiDang() {
        return this.baiDang;
    }
    
    public void setBaiDang(String baiDang) {
        this.baiDang = baiDang;
    }




}


