package com.web.model;
// Generated Jan 1, 2017 9:30:15 PM by Hibernate Tools 4.3.1



/**
 * Sanpham generated by hbm2java
 */
public class Sanpham  implements java.io.Serializable {


     private int idSanPham;
     private String tenSanPham;
     private String moTa;
     private String image;
     private String chiTietSanPham;

    public Sanpham() {
    }

	
    public Sanpham(int idSanPham) {
        this.idSanPham = idSanPham;
    }
    public Sanpham(int idSanPham, String tenSanPham, String moTa, String image, String chiTietSanPham) {
       this.idSanPham = idSanPham;
       this.tenSanPham = tenSanPham;
       this.moTa = moTa;
       this.image = image;
       this.chiTietSanPham = chiTietSanPham;
    }
   
    public int getIdSanPham() {
        return this.idSanPham;
    }
    
    public void setIdSanPham(int idSanPham) {
        this.idSanPham = idSanPham;
    }
    public String getTenSanPham() {
        return this.tenSanPham;
    }
    
    public void setTenSanPham(String tenSanPham) {
        this.tenSanPham = tenSanPham;
    }
    public String getMoTa() {
        return this.moTa;
    }
    
    public void setMoTa(String moTa) {
        this.moTa = moTa;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public String getChiTietSanPham() {
        return this.chiTietSanPham;
    }
    
    public void setChiTietSanPham(String chiTietSanPham) {
        this.chiTietSanPham = chiTietSanPham;
    }




}


